name: Lint python

on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.py"
      - "**.pyi"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - run: poetry install --sync --all-extras --no-root --no-interaction
      - run: poetry run pre-commit run --color=always --all-files
